# The configuration file for mgw
[server]
host = "0.0.0.0"
port = "9843"
publicKeyPath = "/home/wso2/security/localhost.pem"
privateKeyPath = "/home/wso2/security/localhost.key"
username = "admin"
password = "admin"

[envoy]
listenerHost = "0.0.0.0"
listenerPort = 9095
clusterTimeoutInSeconds = 20
listenerTLSEnabled = true
listenerCertPath = "/home/wso2/security/mg.pem"
listenerKeyPath = "/home/wso2/security/mg.key"

[envoy.upstream]
[envoy.upstream.tls]
minimumProtocolVersion = "TLS1_1"
maximumProtocolVersion = "TLS1_2"
ciphers = "ECDHE-ECDSA-AES128-GCM-SHA256, ECDHE-RSA-AES128-GCM-SHA256, ECDHE-ECDSA-AES128-SHA, ECDHE-RSA-AES128-SHA, AES128-GCM-SHA256, AES128-SHA, ECDHE-ECDSA-AES256-GCM-SHA384, ECDHE-RSA-AES256-GCM-SHA384, ECDHE-ECDSA-AES256-SHA, ECDHE-RSA-AES256-SHA, AES256-GCM-SHA384, AES256-SHA"  
# the default endpoint certificates
trustedCertificatesFilePath = "/etc/ssl/certs/ca-certificates.crt"
clientCertPath = "/home/wso2/security/mg.pem"
clientKeyPath = "/home/wso2/security/mg.key"
verifyHostName = true
disableSslVerification = false

[filter]
#Key Store Configuration
[filter.keystore]
location = "wso2carbon.jks"
type = "jks"
password = "wso2carbon"

#Trust store configuration
[filter.truststore]
location = "/home/wso2/mg/security/client-truststore.jks"
type = "jks"
password = "wso2carbon"

# JWT token authorization configurations. You can provide multiple JWT issuers
# Issuer 1
[[filter.jwtTokenConfig]]
    name="Resident Key Manager"
    issuer = "https://localhost:9443/oauth2/token"
    certificateAlias = "wso2carbon"
    # URL of the JWKs endpoint
    jwksURL = ""
    # Validate subscribed APIs
    validateSubscription = false
    # The claim in which the consumer key of the application is coming
    consumerKeyClaim = "azp"

# Configurations for retrieving API and subscription data from API Manager.
[filter.eventHub]
    # Enable/ Disable the feature
    enable = false
    # The API Manager URL
    serviceUrl = "https://localhost:9443/"
    # User name and password of the internal data api.
    username="admin"
    password="admin"
    # The message broker connection URL.
    eventListeningEndpoints = "amqp://admin:admin@carbon/carbon?brokerlist='tcp://localhost:5672'"
