openapi: 3.0.0
info:
  description: This API contains operations related to online book store.
  title: Book-Store
  version: v1
paths:
  /books:
    post:
      responses:
        "200":
          description: successful operation
x-wso2-basePath: /abc-stores
x-wso2-production-endpoints:
  urls:
    - http://legacy-xml-backend:9080
x-wso2-request-interceptor:
  scheme: https
  host: xml-interceptor
  port: 9081
  includes:
    - request_body
x-wso2-response-interceptor:
  scheme: https
  host: xml-interceptor
  port: 9081
