apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: choreo-connect-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
  - hosts:
      - gw.wso2.com
      - adapter.wso2.com
      - apim.wso2.com
    secretName: tls-secret
  rules:
    - host: apim.wso2.com
      http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: wso2apim
                  port:
                    number: 9443
    - host: gw.wso2.com
      http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: router
                  port:
                    number: 9095
    - host: adapter.wso2.com
      http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: adapter
                  port:
                    number: 9843

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: choreo-connect-ingress-internal
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
  - hosts:
      - internal.wso2.com

  rules:
    - host: internal.wso2.com
      http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: router
                  port:
                    number: 9000
