[project]
org-name= "wso2"
version= "3.1.0"

[platform]
target = "java8"

    [[platform.libraries]]
    path = "../../../target/org.wso2.micro.gateway.core-3.1.0-beta2-SNAPSHOT.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/org.everit.json.schema-1.5.0.wso2.v1.jar"

    [[platform.libraries]]
        path = "../../../target/lib/dependencies/jackson-databind-2.9.10.jar"

    [[platform.libraries]]
        path = "../../../target/lib/dependencies/jackson-core-2.9.9.jar"

    [[platform.libraries]]
        path = "../../../target/lib/dependencies/jackson-annotations-2.9.9.jar"

    [[platform.libraries]]
        path = "../../../target/lib/dependencies/json-smart-2.3.jar"

    [[platform.libraries]]
        path = "../../../target/lib/dependencies/json-path-2.4.0.wso2v2.jar"

    [[platform.libraries]]
                 path = "../../../target/lib/dependencies/guava-27.0-jre.jar"

    [[platform.libraries]]
                     path = "../../../target/lib/dependencies/json-20140107.jar"

    [[platform.libraries]]
                     path = "../../../target/lib/dependencies/asm-1.0.2.jar"


[dependencies]
"wso2/jms" = "0.7.0"
